# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80066c98185919ad50582cc682bcd8a65690c2ca8a725df669929f12448b7d53b673354a583b43287d73bf96e2e81886490dfb14f986fd2a1d8f1d0975a7eb3c

test:
  secret_key_base: 85794cdab1bcb816e637f798887e56837787b6da5e4b2315f1b04b069c4bea7a1a4364ac36b40cbb13ceb342ad624615abc95be7ca06186625be426d28fc3c00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
